// AUTO-GENERATED by `nflgrades gen-types`. Do not edit by hand.
// Source of truth: db/migrations/*.sql introspected via information_schema.
// To regenerate: `nflgrades gen-types`
// To check in CI: `nflgrades gen-types --check`

export type CareerGradesRow = {
  player_id: number;
  as_of_date: string;
  grade: number;
  uncertainty: number;
  last_season: number;
  n_seasons: number;
};

export type DepthChartsRow = {
  team_id: number;
  season: number;
  week: number;
  position: string;
  depth_order: number;
  player_id: number;
};

export type NgsPassingRow = {
  player_id: number;
  season: number;
  season_type: string;
  week: number;
  team_id: number;
  avg_time_to_throw: number | null;
  avg_completed_air_yards: number | null;
  avg_intended_air_yards: number | null;
  avg_air_yards_differential: number | null;
  aggressiveness: number | null;
  max_completed_air_distance: number | null;
  avg_air_yards_to_sticks: number | null;
  attempts: number | null;
  pass_yards: number | null;
  pass_touchdowns: number | null;
  interceptions: number | null;
  completions: number | null;
  passer_rating: number | null;
  completion_percentage: number | null;
  expected_completion_percentage: number | null;
  completion_percentage_above_expectation: number | null;
  avg_air_distance: number | null;
  max_air_distance: number | null;
};

export type NgsReceivingRow = {
  player_id: number;
  season: number;
  season_type: string;
  week: number;
  team_id: number;
  avg_cushion: number | null;
  avg_separation: number | null;
  avg_intended_air_yards: number | null;
  percent_share_of_intended_air_yards: number | null;
  receptions: number | null;
  targets: number | null;
  catch_percentage: number | null;
  yards: number | null;
  rec_touchdowns: number | null;
  avg_yac: number | null;
  avg_expected_yac: number | null;
  avg_yac_above_expectation: number | null;
};

export type NgsRushingRow = {
  player_id: number;
  season: number;
  season_type: string;
  week: number;
  team_id: number;
  efficiency: number | null;
  percent_attempts_gte_eight_defenders: number | null;
  avg_time_to_los: number | null;
  rush_attempts: number | null;
  rush_yards: number | null;
  avg_rush_yards: number | null;
  rush_touchdowns: number | null;
  expected_rush_yards: number | null;
  rush_yards_over_expected: number | null;
  rush_yards_over_expected_per_att: number | null;
  rush_pct_over_expected: number | null;
};

export type PipelineRunsRow = {
  run_id: number;
  stage: string;
  season: number | null;
  started_at: string;
  finished_at: string | null;
  status: string;
  rows_written: number | null;
  notes: string | null;
};

export type PlayerSeasonsRow = {
  player_id: number;
  season: number;
  team_id: number;
  position_played: string;
  games: number;
  games_started: number;
  snaps_offense: number;
  snaps_defense: number;
  snaps_special: number;
};

export type PlayersRow = {
  player_id: number;
  gsis_id: string | null;
  full_name: string;
  position: string;
  birth_date: string | null;
  height_inches: number | null;
  weight_lbs: number | null;
  draft_year: number | null;
  draft_round: number | null;
  draft_pick: number | null;
  current_team_id: number | null;
  last_updated: string;
  pfr_id: string | null;
};

export type PlaysRow = {
  game_id: string;
  play_id: number;
  season: number;
  season_type: string;
  week: number | null;
  game_date: string | null;
  posteam: string | null;
  defteam: string | null;
  home_team: string | null;
  away_team: string | null;
  qtr: number | null;
  down: number | null;
  ydstogo: number | null;
  yardline_100: number | null;
  score_differential: number | null;
  game_seconds_remaining: number | null;
  half_seconds_remaining: number | null;
  wp: number | null;
  play_type: string | null;
  qb_dropback: boolean | null;
  pass_attempt: boolean | null;
  rush_attempt: boolean | null;
  sack: boolean | null;
  qb_scramble: boolean | null;
  qb_spike: boolean | null;
  qb_kneel: boolean | null;
  aborted_play: boolean | null;
  two_point_attempt: boolean | null;
  penalty: boolean | null;
  passer_player_id: string | null;
  rusher_player_id: string | null;
  receiver_player_id: string | null;
  sack_player_id: string | null;
  interception_player_id: string | null;
  yards_gained: number | null;
  epa: number | null;
  wpa: number | null;
  cpoe: number | null;
  success: boolean | null;
  air_yards: number | null;
  yards_after_catch: number | null;
  complete_pass: boolean | null;
  incomplete_pass: boolean | null;
  interception: boolean | null;
  fumble_lost: boolean | null;
  pass_touchdown: boolean | null;
  rush_touchdown: boolean | null;
  touchdown: boolean | null;
  play_desc: string | null;
  fumble: boolean | null;
  xyac_mean_yardage: number | null;
};

export type SchemaMigrationsRow = {
  filename: string;
  sha256: string;
  applied_at: string;
};

export type SeasonGradesRow = {
  player_id: number;
  season: number;
  position: string;
  composite_grade: number;
  composite_z: number;
  percentile: number;
  confidence: number | null;
  data_tier: number;
  qualified: boolean;
  computed_at: string;
  role: string | null;
  data_tier_reason: string | null;
};

export type StatComponentsRow = {
  player_id: number;
  season: number;
  component_name: string;
  raw_value: number | null;
  adjusted_value: number | null;
  z_score: number | null;
  sample_size: number | null;
  used_in_composite: boolean;
};

export type TeamAliasesRow = {
  alias: string;
  team_id: number;
};

export type TeamsRow = {
  team_id: number;
  abbr: string;
  name: string;
  conference: string;
  division: string;
  primary_color: string | null;
  secondary_color: string | null;
};
