/**
 * Public TypeScript types for the web app.
 *
 * Two layers:
 *   - `db.generated.ts` mirrors raw table shapes (regenerated by
 *     `nflgrades gen-types`). Never edit by hand.
 *   - This file curates names, narrows union types, and adds view-shaped
 *     types (joins, aggregates) used by API routes and components.
 *
 * See docs/adr/0005-hand-written-ts-types-with-codegen-guardrail.md
 */

import type {
  TeamsRow,
  PlayersRow,
  SeasonGradesRow,
  CareerGradesRow,
  DepthChartsRow,
} from "./db.generated";

export type Conference = "AFC" | "NFC";
export type Division = "North" | "South" | "East" | "West";
export type DataTier = 1 | 2 | 3;

export type Team = Omit<TeamsRow, "conference" | "division"> & {
  conference: Conference;
  division: Division;
};

export type Player = Pick<
  PlayersRow,
  "player_id" | "gsis_id" | "full_name" | "position" | "current_team_id"
>;

export type SeasonGrade = Omit<SeasonGradesRow, "data_tier"> & {
  data_tier: DataTier;
};

export type CareerGrade = CareerGradesRow;

export type DepthChartEntry = DepthChartsRow;

// ---------------------------------------------------------------------------
// View-shaped types (joins of multiple tables used by the UI).
// Defined here (not in db.generated.ts) because they don't correspond to any
// single table — they're the shape returned by `lib/queries.ts` functions.
// ---------------------------------------------------------------------------

/**
 * One leaderboard row: a season grade joined with player name, primary
 * team, and a handful of headline components from stat_components.
 *
 * Which component fields carry values depends on `position`:
 *   QB → n_dropbacks, epa_per_dropback, cpoe, success_rate
 *   RB → n_touches, rb_ryoe_per_attempt, rb_rush_epa_per_attempt,
 *        rb_rush_success_rate
 *   WR → n_targets, rec_epa_per_target, yac_over_expected_per_rec,
 *        target_earn_rate
 *   TE → same as WR, plus `role` populated from season_grades
 *
 * Unused fields are `null` by construction (they come from LEFT JOINs
 * that didn't match because the component doesn't exist for that
 * position). Rendering code should look only at the fields relevant
 * to the position and ignore the rest.
 */
export type LeaderboardEntry = {
  player_id: number;
  full_name: string;
  position: string;
  season: number;
  composite_grade: number;
  composite_z: number;
  percentile: number;
  qualified: boolean;
  confidence: number | null;
  data_tier: number;
  team_abbr: string | null;
  /** TE role label (receiving_te / balanced_te / blocking_te); null for QB/RB/WR. */
  role: string | null;
  // --- QB columns ---
  n_dropbacks: number | null;
  epa_per_dropback: number | null;
  cpoe: number | null;
  success_rate: number | null;
  // --- RB columns ---
  n_touches: number | null;
  rb_ryoe_per_attempt: number | null;
  rb_rush_epa_per_attempt: number | null;
  rb_rush_success_rate: number | null;
  // --- WR / TE columns (column names are position-agnostic; the
  // underlying component is wr_* or te_* depending on sg.position) ---
  n_targets: number | null;
  rec_epa_per_target: number | null;
  yac_over_expected_per_rec: number | null;
  target_earn_rate: number | null;
};

/** One stat_components row rehydrated for a player detail page. */
export type StatComponentDetail = {
  component_name: string;
  raw_value: number | null;
  adjusted_value: number | null;
  z_score: number | null;
  sample_size: number | null;
  /** false when stored for audit but omitted from headline composite (TE earn, ADR-0016). */
  used_in_composite?: boolean;
};

/** One season grade plus its component breakdown, for the player page. */
export type SeasonGradeDetail = {
  season: number;
  position: string;
  composite_grade: number;
  composite_z: number;
  percentile: number;
  qualified: boolean;
  confidence: number | null;
  data_tier: number;
  team_abbr: string | null;
  components: StatComponentDetail[];
};

/** Minimal player metadata — enough to render a header. */
export type PlayerMeta = {
  player_id: number;
  gsis_id: string | null;
  full_name: string;
  position: string;
  current_team_abbr: string | null;
};

/** What /players/[id] renders. */
export type PlayerDetail = {
  player: PlayerMeta;
  grades: SeasonGradeDetail[];
};
