/**
 * Public TypeScript types for the web app.
 *
 * Two layers:
 *   - `db.generated.ts` mirrors raw table shapes (regenerated by
 *     `nflgrades gen-types`). Never edit by hand.
 *   - This file curates names, narrows union types, and adds view-shaped
 *     types (joins, aggregates) used by API routes and components.
 *
 * See docs/adr/0005-hand-written-ts-types-with-codegen-guardrail.md
 */

import type {
  TeamsRow,
  PlayersRow,
  SeasonGradesRow,
  CareerGradesRow,
  DepthChartsRow,
} from "./db.generated";

export type Conference = "AFC" | "NFC";
export type Division = "North" | "South" | "East" | "West";
export type DataTier = 1 | 2 | 3;

export type Team = Omit<TeamsRow, "conference" | "division"> & {
  conference: Conference;
  division: Division;
};

export type Player = Pick<
  PlayersRow,
  "player_id" | "gsis_id" | "full_name" | "position" | "current_team_id"
>;

export type SeasonGrade = Omit<SeasonGradesRow, "data_tier"> & {
  data_tier: DataTier;
};

export type CareerGrade = CareerGradesRow;

export type DepthChartEntry = DepthChartsRow;

// ---------------------------------------------------------------------------
// View-shaped types (joins of multiple tables used by the UI).
// Defined here (not in db.generated.ts) because they don't correspond to any
// single table — they're the shape returned by `lib/queries.ts` functions.
// ---------------------------------------------------------------------------

/**
 * One leaderboard row: a season grade joined with player name, primary
 * team, and a handful of headline components from stat_components.
 *
 * Which component fields carry values depends on `position`:
 *   QB → n_dropbacks, epa_per_dropback, cpoe, success_rate
 *   RB → n_touches, rb_ryoe_per_attempt, rb_rush_epa_per_attempt,
 *        rb_rush_success_rate, rec_epa_per_target,
 *        rb_yac_over_expected_per_rec, rb_fumble_rate
 *        (rb_catch_pct removed v1.1 — confirmed noise)
 *   WR → n_targets, rec_epa_per_target, yac_over_expected_per_rec,
 *        separation, success_rate_per_target, target_earn_rate, drop_rate
 *   TE → same as WR (drop_rate added v1.1, replacing fumble_rate — ADR-0016)
 *   CB → n_targets, cb_passer_rating_allowed, cb_yac_per_rec_allowed,
 *        cb_target_rate, cb_pbu_rate,
 *        plus `role` (outside_cb / hybrid_cb / slot_cb)
 *   S  → n_snaps, s_passer_rating_allowed, s_target_rate, s_pbu_rate,
 *        s_tackles_per_snap, s_missed_tackle_rate, s_backfield_disruption_per_snap
 *   EDGE → edge_pressure_rate, edge_sack_rate, edge_tfl_rate,
 *        edge_tackles_per_snap, edge_missed_tackle_rate (n_snaps reused for snap count)
 *   iDL → idl_tfl_rate, idl_pressure_rate, idl_sack_rate,
 *        idl_tackles_per_snap, idl_missed_tackle_rate (n_snaps reused for snap count)
 *   LB  → lb_tfl_rate, lb_passer_rating_allowed, lb_missed_tackle_rate,
 *        lb_pbu_rate, lb_tackle_rate, lb_pressure_rate (n_snaps reused)
 *   K   → k_fg_pct_40_plus, k_fg_pct, k_pat_pct, k_fg_long, n_fg_att
 *        (kickers have no snap count — FG attempts are the qualifying sample)
 *   P   → p_net_avg, p_inside_20_rate, p_blocked_rate (formula);
 *        p_gross_avg, p_long_punt, p_touchback_rate (context); n_punts
 *
 * Unused fields are `null` by construction (they come from LEFT JOINs
 * that didn't match because the component doesn't exist for that
 * position). Rendering code should look only at the fields relevant
 * to the position and ignore the rest.
 */
export type LeaderboardEntry = {
  player_id: number;
  full_name: string;
  position: string;
  season: number;
  composite_grade: number;
  composite_z: number;
  percentile: number;
  qualified: boolean;
  confidence: number | null;
  data_tier: number;
  team_abbr: string | null;
  /** Role label; TE: receiving_te/balanced_te/blocking_te; CB: outside_cb/hybrid_cb/slot_cb; null otherwise. */
  role: string | null;
  // --- QB columns ---
  n_dropbacks: number | null;
  epa_per_dropback: number | null;
  cpoe: number | null;
  success_rate: number | null;
  // --- RB columns ---
  n_touches: number | null;
  rb_ryoe_per_attempt: number | null;
  rb_rush_epa_per_attempt: number | null;
  rb_rush_success_rate: number | null;
  rb_yac_over_expected_per_rec: number | null;
  rb_yards_after_contact_per_carry: number | null;
  rb_fumble_rate: number | null;
  // --- WR / TE columns (position-agnostic names; underlying component is
  // wr_* or te_* depending on sg.position) ---
  // drop_rate from FTN charting (2022+), used by both WR (v1.2) and TE (v1.1).
  n_targets: number | null;
  rec_epa_per_target: number | null;
  yac_over_expected_per_rec: number | null;
  separation: number | null;
  success_rate_per_target: number | null;
  target_earn_rate: number | null;
  drop_rate: number | null;
  // --- CB columns ---
  cb_passer_rating_allowed: number | null;
  cb_yac_per_rec_allowed: number | null;
  cb_target_rate: number | null;
  cb_pbu_rate: number | null;
  // --- S columns ---
  n_snaps: number | null;
  s_passer_rating_allowed: number | null;
  s_target_rate: number | null;
  s_pbu_rate: number | null;
  s_tackles_per_snap: number | null;
  s_missed_tackle_rate: number | null;
  s_backfield_disruption_per_snap: number | null;
  // --- EDGE columns ---
  edge_pressure_rate: number | null;
  edge_sack_rate: number | null;
  edge_tfl_rate: number | null;
  edge_tackles_per_snap: number | null;
  edge_missed_tackle_rate: number | null;
  // --- iDL columns ---
  idl_tfl_rate: number | null;
  idl_pressure_rate: number | null;
  idl_sack_rate: number | null;
  idl_tackles_per_snap: number | null;
  idl_missed_tackle_rate: number | null;
  // --- LB columns ---
  lb_tfl_rate: number | null;
  lb_passer_rating_allowed: number | null;
  lb_missed_tackle_rate: number | null;
  lb_pbu_rate: number | null;
  lb_tackle_rate: number | null;
  lb_pressure_rate: number | null;
  // --- K columns ---
  // n_fg_att is the qualifying sample for kickers (FG attempts, not snaps).
  // FGOE / att (k_fg_over_expected_per_att) is the SOLE formula component
  // post-v1.1. Other K columns are context — displayed but not scored.
  n_fg_att: number | null;
  k_fg_over_expected_per_att: number | null;
  k_fg_pct: number | null;
  k_fg_pct_40_plus: number | null;
  k_pat_pct: number | null;
  k_fg_long: number | null;
  // --- P columns ---
  // n_punts is the qualifying sample for punters.
  // p_net_avg + p_inside_20_rate + p_blocked_rate are FORMULA components.
  // p_gross_avg, p_long_punt, p_touchback_rate are CONTEXT (displayed, not scored).
  n_punts: number | null;
  p_net_avg: number | null;
  p_inside_20_rate: number | null;
  p_blocked_rate: number | null;
  p_gross_avg: number | null;
  p_long_punt: number | null;
  p_touchback_rate: number | null;
};

/** One stat_components row rehydrated for a player detail page. */
export type StatComponentDetail = {
  component_name: string;
  raw_value: number | null;
  adjusted_value: number | null;
  z_score: number | null;
  sample_size: number | null;
  /** false when stored for audit but omitted from headline composite (TE earn, ADR-0016). */
  used_in_composite?: boolean;
};

/** One season grade plus its component breakdown, for the player page. */
export type SeasonGradeDetail = {
  season: number;
  position: string;
  composite_grade: number;
  composite_z: number;
  percentile: number;
  qualified: boolean;
  confidence: number | null;
  data_tier: number;
  team_abbr: string | null;
  /** TE role string (receiving_te / balanced_te / blocking_te), null otherwise. */
  role: string | null;
  components: StatComponentDetail[];
  /**
   * Offense context for ADR-0017 mitigation. Populated for WR/TE/RB
   * grades that have a team_abbr; null for QB grades (context would
   * be circular) or when team lookup failed.
   */
  context: TeamContext | null;
};

/**
 * Lead QB for a team in a given season (the one with the most dropbacks).
 * Grade/qualified may be null when the QB didn't meet the grade threshold
 * — we still surface them so the reader sees the identity and understands
 * why the grade is missing.
 */
export type TopQb = {
  player_id: number;
  full_name: string;
  composite_grade: number | null;
  qualified: boolean | null;
  dropbacks: number;
};

/**
 * Team offense + QB context attached to a non-QB season grade.
 * See ADR-0017 for the trigger logic on `player_high_volume` and the
 * inline note.
 */
export type TeamContext = {
  team_abbr: string;
  season: number;
  /** Team offensive EPA/play on standard downs 1-4, pass/run only. */
  team_epa_per_play: number;
  /** 1 = best offense in the league that season. */
  team_epa_rank: number;
  /** Total teams ranked (usually 32 for a full season). */
  team_epa_total: number;
  top_qb: TopQb | null;
  /**
   * True when this player is top-15 at their position by volume
   * (targets for WR/TE, touches for RB) that season. Used together
   * with a bad top-QB grade to fire the ADR-0017 inline note.
   */
  player_high_volume: boolean;
};

/** Minimal player metadata — enough to render a header. */
export type PlayerMeta = {
  player_id: number;
  gsis_id: string | null;
  full_name: string;
  position: string;
  current_team_abbr: string | null;
};

/** What /players/[id] renders. */
export type PlayerDetail = {
  player: PlayerMeta;
  grades: SeasonGradeDetail[];
};
