"""Generate web/src/types/db.generated.ts from the live Postgres schema.

The hand-written `web/src/types/index.ts` is the public surface (curated names,
nullable variants, view-shaped types). This generated file mirrors the raw
table shapes and is the guardrail: if you change a migration without
updating index.ts, the diff will surface it.

See docs/adr/0005-hand-written-ts-types-with-codegen-guardrail.md

Usage
-----
    nflgrades gen-types                 # write file
    nflgrades gen-types --check         # exit non-zero if generated content
                                        # differs from what's on disk (CI)
"""

from __future__ import annotations

from sqlalchemy import text

from .config import REPO_ROOT
from .db import get_engine
from .logging import get_logger

log = get_logger(__name__)

OUTPUT_FILE = REPO_ROOT / "web" / "src" / "types" / "db.generated.ts"

HEADER = """\
// AUTO-GENERATED by `nflgrades gen-types`. Do not edit by hand.
// Source of truth: db/migrations/*.sql introspected via information_schema.
// To regenerate: `nflgrades gen-types`
// To check in CI: `nflgrades gen-types --check`

"""

# Postgres type -> TypeScript type. Anything not in this map produces `unknown`
# and a warning so we know to extend it.
PG_TO_TS: dict[str, str] = {
    "integer": "number",
    "bigint": "number",
    "smallint": "number",
    "double precision": "number",
    "real": "number",
    "numeric": "number",
    "text": "string",
    "character varying": "string",
    "character": "string",
    "boolean": "boolean",
    "date": "string",
    "timestamp with time zone": "string",
    "timestamp without time zone": "string",
    "time with time zone": "string",
    "time without time zone": "string",
    "json": "unknown",
    "jsonb": "unknown",
    "uuid": "string",
}


def _snake_to_pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def _ts_type(pg_type: str, nullable: bool) -> str:
    base = PG_TO_TS.get(pg_type)
    if base is None:
        log.warning("Unknown postgres type %r, emitting `unknown`", pg_type)
        base = "unknown"
    return f"{base} | null" if nullable else base


def generate() -> str:
    """Return the full generated TypeScript source as a string."""
    engine = get_engine()
    with engine.connect() as conn:
        tables = [
            row.table_name
            for row in conn.execute(
                text(
                    """
                    SELECT table_name FROM information_schema.tables
                    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
                    ORDER BY table_name
                    """
                )
            )
        ]

        sections: list[str] = []
        for table in tables:
            cols = conn.execute(
                text(
                    """
                    SELECT column_name, data_type, is_nullable
                    FROM information_schema.columns
                    WHERE table_schema = 'public' AND table_name = :t
                    ORDER BY ordinal_position
                    """
                ),
                {"t": table},
            ).all()
            type_name = _snake_to_pascal(table) + "Row"
            lines = [f"export type {type_name} = {{"]
            for col in cols:
                ts = _ts_type(col.data_type, col.is_nullable == "YES")
                lines.append(f"  {col.column_name}: {ts};")
            lines.append("};")
            sections.append("\n".join(lines))

    return HEADER + "\n\n".join(sections) + "\n"


def write(check: bool = False) -> int:
    """Write or verify the generated file. Returns exit code (0 = ok)."""
    new_content = generate()

    if check:
        if not OUTPUT_FILE.exists():
            log.error("%s does not exist; run `nflgrades gen-types`.", OUTPUT_FILE)
            return 1
        existing = OUTPUT_FILE.read_text(encoding="utf-8")
        if existing != new_content:
            log.error(
                "%s is out of date. Run `nflgrades gen-types` and commit the result.",
                OUTPUT_FILE,
            )
            return 1
        log.info("Generated types are up to date.")
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(new_content, encoding="utf-8")
    log.info("Wrote %s", OUTPUT_FILE)
    return 0
