"use client";

import { useState } from "react";

/**
 * Pixelated player headshot. Loads from `/headshots/{playerId}.png` —
 * a 736×736 RGBA PNG with transparent background, generated by the
 * pipeline (`nflgrades ingest pixel-headshots`).
 *
 * `imageRendering: "pixelated"` keeps the source pixels square at every
 * display size. The image's natural resolution is high enough to scale
 * up cleanly to hero size (96-160px) without re-resampling.
 *
 * If the player doesn't have a generated headshot yet (file 404s), the
 * onError handler hides the element entirely — no broken-image icon,
 * no layout shift on most pages (the flex parent collapses).
 */
type Props = {
  playerId: number;
  /** Display size in CSS pixels. */
  size?: number;
  className?: string;
};

export function PlayerHeadshot({ playerId, size = 96, className = "" }: Props) {
  const [errored, setErrored] = useState(false);
  if (errored) return null;
  return (
    /* eslint-disable-next-line @next/next/no-img-element */
    <img
      src={`/headshots/${playerId}.png`}
      alt=""
      width={size}
      height={size}
      style={{ imageRendering: "pixelated" }}
      className={"shrink-0 " + className}
      onError={() => setErrored(true)}
    />
  );
}
